/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  prefix: "",
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  mode: "jit",
  corePlugins: {
    aspectRatio: false,
    preflight: true,
  },
  theme: {
    screens: {
      xxs: "320px",
      xs: "425px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      borderColor: ["autofill"],
      shadowFill: ["autofill"],
      textFill: ["autofill"],
      scrollbar: {
        default: {
          size: "spacing.1",
          track: { background: "lightgray" },
          thumb: { background: "gray" },
          hover: { background: "darkgray" },
        },
        thin: {
          size: "2px",
          track: { background: "lightgray" },
          thumb: { background: "gray" },
          hover: { background: "darkgray" },
        },
        primary: {
          size: "1rem",
          track: { background: "#FFD1D7" },
          thumb: { background: "#FFB6C1" },
          hover: { background: "#FF7086" },
        },
        secondary: {
          size: ".5rem",
          track: { background: "#FFD1D7" },
          thumb: { background: "#FFB6C1" },
          hover: { background: "#FF7086" },
        },
        light: {
          size: "1rem",
          track: { background: "#ffffff" },
          thumb: { background: "#FAF7F7" },
          hover: { background: "#CCD5DE" },
        },
        dark: {
          size: "1rem",
          track: { background: "#5E738A" },
          thumb: { background: "#212B36" },
          hover: { background: "#00000075" },
        },
      },
      tooltipArrows: (theme) => ({
        "danger-arrow": {
          borderColor: theme("colors.red.400"),
          borderWidth: 1,
          backgroundColor: theme("colors.red.200"),
          size: 10,
          offset: 10,
        },
      }),
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        card: {
          shadow: "#00000025",
          input: "#00000000",
        },
        light: {
          default: "#FAF7F7",
          variant: "#ffffff",
        },
        dark: {
          default: "#212B36",
          shadow: "#00000075",
          variant: "#000000",
        },
        primary: {
          default: "#FFB6C1",
          variant: "#FFC0CB",
          accent: "#FF7086",
          t2: "#FFCDD5",
          t3: "#FFD1D7",
          t4: "#FFDBE0",
          t5: "#FFE5E9",
        },
        secondary: {
          default: "#FF45AA",
          variant: "#FF7AC2",
          accent: "#FF1493",
          t2: "#FF9FD3",
          t3: "#FFAFDB",
          t4: "#FFC1E3",
          t5: "#FFDBEF",
        },
        neutral: {
          primary: "#212B36",
          secondary: "#5E738A",
          800: "#333F4D",
          700: "#425263",
          600: "#516579",
          300: "#8D9DAE",
          200: "#ADB9C6",
          100: "#CCD5DE",
          50: "#F4F6F8",
        },
      },
    },
  },
  daisyui: {
    themes: false,
    base: true,
    styled: true,
    utils: true,
    rtl: false,
    prefix: "",
    logs: false,
    themes: [
      {
        mytheme: {
          primary: "#FFB6C1",
          secondary: "#FF45AA",
          accent: "#FF7086",
          neutral: "#FF1493",
          "base-100": " #FAF7F7",
          info: "#248EF2",
          success: "#39B54A",
          warning: "#FFB400",
          error: "#FF0000",
        },
      },
    ],
  },
  plugins: [
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@kamona/tailwindcss-perspective"),
    require("@gradin/tailwindcss-scrollbar"),
    require("tailwindcss-labeled-groups")(["custom", "1"]),
    require("tailwindcss-css-filters"),
    require("tailwindcss-highlights"),
    require("tailwindcss-autofill"),
    require("tailwindcss-tooltip-arrow-after"),
    require("tailwindcss-debug-screens"),
    require("tailwind-scrollbar-hide"),
    require("tailwindcss-gradients"),
    require("tailwindcss-border-gradients")(),
    require("daisyui"),
  ],
};
