import TAGS from "./tags";

export default {
  GET: "GET",
  POST: "POST",
  PATCH: "PATCH",
  PUT: "PUT",
  DELETE: "DELETE",
  TAGS: [
    TAGS.API,
    TAGS.USERS,
    TAGS.SERVICES,
    TAGS.APPOINTMENTS,
    TAGS.FEEDBACKS,
    TAGS.TRANSACTIONS,
    TAGS.COMMENTS,
    TAGS.PRODUCTS,
    TAGS.DELIVERIES,
    TAGS.BRANDS,
    TAGS.TIMES,
    TAGS.SCHEDULES,
    TAGS.OPTIONS,
    TAGS.EXCLUSIONS,
    TAGS.MONTHS,
    TAGS.INVENTORY,
  ],
};
