export default {
  LOGIN_ROUTE: "/login",
  LOGOUT_ROUTE: "/logout",
  USERS_ROUTE: "users",
  USER_ID_ROUTE: "user/:id",
  EDIT_USER_ID_ROUTE: "user/edit/:id",
  UPDATE_PASSWORD_ROUTE: "/updatePassword/:id",
  ACTIVATE_USER_ID_ROUTE: "/user/activate/:id",
  SERVICES_ROUTE: "services",
  SERVICE_ID_ROUTE: "service/:id",
  EDIT_SERVICE_ID_ROUTE: "service/edit/:id",
  APPOINTMENTS_ROUTE: "appointments",
  APPOINTMENT_ID_ROUTE: "appointment/:id",
  EDIT_APPOINTMENT_ID_ROUTE: "appointment/edit/:id",
};
