export default {
  API: "api",
  AUTH: "auth",
  USERS: "Users",
  USER: "user",
  SERVICES: "Services",
  SERVICE: "service",
  APPOINTMENTS: "Appointments",
  APPOINTMENT: "appointment",
  FEEDBACKS: "Feedbacks",
  FEEDBACK: "Feedback",
  TRANSACTIONS: "Transactions",
  TRANSACTION: "Transaction",
  COMMENTS: "Comments",
  COMMENT: "Comment",
  PRODUCTS: "Products",
  DELIVERIES: "Deliveries",
  DELIVERY: "Delivery",
  BRANDS: "Brands",
  TIMES: "Times",
  SCHEDULES: "Schedules",
  OPTIONS: "Options",
  EXCLUSIONS: "Exclusions",
  MONTHS: "Months",
  HIRINGS: "Hirings",
  REPORTS: "Reports",
  EQUIPMENTS: "Equipments",
  FOUNDS: "Founds",
  LOGBOOKS: "Logbooks",
  CHARTS: "Charts",
  INVENTORY:"Inventories",
};
