export default {
  API: "api",
  AUTH: "auth",
  USERS: "Users",
  USER: "user",
  SERVICES: "Services",
  SERVICE: "service",
  APPOINTMENTS: "Appointments",
  APPOINTMENT: "appointment",
  FEEDBACKS: "Feedbacks",
  FEEDBACK: "Feedback",
  TRANSACTIONS: "Transactions",
  TRANSACTION: "Transaction",
  COMMENTS: "Comments",
  COMMENT: "Comment",
  PRODUCTS:"Products",
  SEARCH:"Search"
  PRODUCTS: "Products",
  DELIVERIES: "Deliveries",
  DELIVERY: "Delivery",
};
